template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '.github/**']

  - labels: ['C: source']
    patterns: ['**/*.py|-tests']

  - labels: ['C: docs']
    patterns: ['**/*.md|docs/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: css']
    patterns: ['css/**']

  - labels: ['C: examples']
    patterns: ['@(examples|samples)/**']

  - labels: ['C: desktop']
    patterns: ['desktop/**']

  - labels: ['C: settings-handler']
    patterns: ['markdown_settings.py']

  - labels: ['C: markdown-wrapper']
    patterns: ['markdown_wrapper.py']

  - labels: ['C: markdown-preview']
    patterns: ['markdown_preview.py']

  - labels: ['C: settings']
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

# Label management

labels:
- name: 'C: css'
  color: subcategory
  description: CSS stylesheets.

- name: 'C: examples'
  color: subcategory
  description: Examples.

- name: 'C: desktop'
  color: subcategory
  description: Desktop library.

- name: 'C: settings-handler'
  color: subcategory
  description: Settings handler.

- name: 'C: markdown-wrapper'
  color: subcategory
  description: Markdown library wrapper.

- name: 'C: markdown-preview'
  color: subcategory
  description: Main code.

- name: 'C: settings'
  color: subcategory
  description: Sublime settins files.
